### ISSUE TITLE
Is it possible to trigger a reload?

### ISSUE THREAD

**Issue by jaredcurtis** [haproxytech/dataplaneapi#103]
Hello,

We're in the process of moving our HAProxy configurations away from a legacy method involving templated config files. Until we've completed this work we need to be able to trigger a reload of HAProxy in order to refresh config files.

Does the Dataplane API offer a method to trigger a reload?

**Comment by amelhusic** [comment]
Hi @jaredcurtis ,

There is a `force_reload` query string parameter for that purpose.
For example, if you want to [create a server](https://www.haproxy.com/documentation/dataplaneapi/latest/#operation/createServer) and reload, then you can set it to `true`.

There is also a `reload-delay` CLI option you can use to trigger reload periodically

> Checking reload success. To avoid constant reloading we reload in intervals that are configurable when with reload-delay option. When a change to configuration is made and force_reload url query string parameter is false we issue a request for reload, and return the reload ID in response header. You can then use reloads endpoints to check the status of that reload ID. If force_reload is true, we override all of this and reload immediately.


For more info, please refer to the [docs](https://www.haproxy.com/documentation/dataplaneapi/latest/#tag/Reloads).

**Comment by jaredcurtis** [comment]
@amelhusic 
Thanks, at this moment we're only using the API to update map files. We're adding backends by updating config files using a template. I would like to trigger a reload without modifying the configuration.

**Comment by amelhusic** [comment]
AFAIK, that is not possible, but as a workaround you could "update" (without modifying) `bind` line, for example, and set `force_reload` to `true` to issue a reload command.

**Comment by GilchristT** [comment]
Plus one for this feature.

I'll have a look at the workaround suggested though, thanks.

**Comment by GilchristT** [comment]
I've tried this but it's not really practical for what I want to do and I'd guess the OP will run into the same issue.
The issue is with the version info. The problem is that I upload a new HAProxy config to the server the first PUT a message to update an existing bind (without changing as suggested) after a container restart works OK but all subsequent attempts fail with something similar to the error below.

`        "json": {
            "code": 409, 
            "message": "15: Version mismatch, transaction version: 1, configured version: 2"
        },  `

This isn't because I'm not sending the right version information, I get a different error when I do that. It appears to be because the haproxy.cfg file gets a # _version=x added to the top when any change is made via the dataplane but the config file I've just uploaded doesn't have this version information?

It's not really going to be practical to fetch the current version info and add it to the top of my file every time?

Ideally a command with the skip_version parameter similar to posting a full raw config would resolve this?

Thanks

Tommy

**Comment by mjuraga** [comment]
Hi, if you are using some kind of templating + the dataplaneapi it could cause some issues because of several reasons:

- version number as @GilchristT mentioned that is at the top of the file and that the dataplaneapi uses
- ordering of lines inside the configuration file, dataplaneapi does not preserve the ordering of configuration line once it writes it in a section

Ideally if you are using templating you can use the raw configuration endpoint to post the configuration generated by the templating engine to the dataplaneapi, this way the version will be preserved and a reload will be triggered. Also you can skip version checks, even skip reloads and make changes through the runtime API using the `X-Runtime-Actions` header if applicable. You can check those headers defined here: https://github.com/haproxytech/dataplaneapi-specification/blob/5e9c04cdcc269ccfc9dd740ed00581e42787728b/paths/configuration.yaml#L2856

**Comment by GilchristT** [comment]
@mjuraga Thanks for that.

That was the path I was going down but then into the issue of triggering a reload/refresh to pick up newly updated SSL certificates. I don't see any way to update an SSL certificate via the dataplane API?

I've seen a blog post on how to do this with the runtime API but can't see the equivalent in the dataplane API?

**Comment by mjuraga** [comment]
Adding SSL certification management to the dataplaneapi is in our roadmap for the next version.

**Comment by GilchristT** [comment]
Great to hear.

Many thanks to you and all the other contributors for your work on this project.
