### ISSUE TITLE
Not able to update map by ID

### ISSUE THREAD

**Issue by titansmc** [haproxytech/dataplaneapi#108]
Hi,
We are using puppet module to configure HAProxy and this module doesn't allow you to put the maps into /etc/haproxy/maps/* it just defaults to /etc/haproxy. How can I edit a map that is not in  /etc/haproxy/maps/* ?

**Comment by amelhusic** [comment]
Hi,
You can specify maps directory with `--maps-dir` flag. If not used, the default dir is `/etc/haproxy/maps`.

**Comment by titansmc** [comment]
right, this is what I am doing for now, but it would be nice to have it, since with the get maps call you can get them all, I would also expect I can modify them all regardless where they are.

**Comment by mjuraga** [comment]
We can add this to our roadmap as an improvement of the maps feature.

**Comment by amelhusic** [comment]
Hi @titansmc ,
With https://github.com/haproxytech/dataplaneapi/commit/ce286865b8636223d37b716b9ff09e0eb93af824 and https://github.com/haproxytech/client-native/commit/ad03bce441ccff37b1b3b3dad9317b93a710734e it is possible to work with existing maps without `--maps-dir`.
Obviously, you need this option only when you want to create a new map file, since there is no default dir.
