### ISSUE TITLE
Bug... DELETE /v2/services/haproxy/runtime/maps_entries/${id} does not work when haproxy is reloaded shortly afterwards.

### ISSUE THREAD

**Issue by june07** [haproxytech/dataplaneapi#124]
Upon receiving a valid response (204 Map key/value deleted) from the DELETE endpoint, and then immediately reloading haproxy, the records which were confirmed deleted end up persisting and in fact are not deleted.

If I introduce a pause into my program flow, the records are removed.  However I think this is a bug...

**Comment by amelhusic** [comment]
Hi,

Why do you reload haproxy when dealing with runtime maps? The purpose of runtime maps is that you don't need to reload.
Implementation of runtime maps in dataplaneapi is such that entries are synced from runtime entries to file entries. There is a CLI option for that in dataplaneapi, `update-map-files-period`, with default value of `10s`. You can configure it as you wish.

In your case, you deleted entry from memory, then before syncing operation is executed, you reloaded. And when you reload, haproxy will read entries from map file and use those entries.

**Comment by june07** [comment]
I understand the purpose of runtime maps and the lack of need to reload...
The reload is being done via a transaction that is specific to configuration, however coincides with also needing to update mapping entries.

My point in this case is that if the API is returning a 204 status, nothing other than a POST/PUT should cause the records to return.  Not even a reload.  Otherwise I would assume a 202 would be returned and not 204.

**Comment by amelhusic** [comment]
Hi,
We are working on this issue. We will add a new parameter, e.g. forceSync to support immediately syncing.

**Comment by etfloyd** [comment]
I'm seeing a similar issue, a race condition. Our code modifies the backends (may add, update, or delete) then commits and immediately updates a map. The map relates incoming host names to backends, so it needs to be updated after the backend changes are done. The map updates are lost much of the time, but not always. I know that the commit usually triggers a reload, so I'm speculating that the reload is proceeding asynchronously after the commit completes and, depending on how long it takes, may reload either the old map or the updated one. A 'forceSync' would certainly reduce the window, but might not completely eliminate it.

As a work-around, I'm thinking of coding my own 'forceSync'-like operation, building the map file and writing it to disk after updating the map through the api and prior to the commit. I'd rather wait for your 'forceSync' support, though. How long till the next release?

**Comment by june07** [comment]
I can't imagine this is a unique situation and I hope the fix is made to the core. Workarounds are just that. This is definitely a big that should be fixed. Glad the team @amelhusic is working on a fix.

**Comment by etfloyd** [comment]
I've implemented the workaround described above and have not seen a recurrence of the problem. It works like this:

0. Build the information in memory needed to define the changes and determine whether or not an update is required
1. Start transaction
2. Update the backends
3. Update the map using the API
4. Write an updated map file using the same information from step 4
5. Commit
If anything throws an exception between step 2 and 6, cancel the transaction

It's working, so far, but there are two problems with this approach that I don't think will be resolved in the current design, even by a 'forceSync':

First, since the map update now occurs prior to transaction commit, there is a brief window during which the map is updated in memory and the backends are not. This creates a mismatch and possibility of mis-routing requests during that window. (This could be mitigated in the work-around by simply managing the map entirely outside the API, eliminating step 4.)

Second, if there is a failure after some or all of step 4 and 5 are done, the configuration updates will be canceled and the mismatch will extend indefinitely.

For our use case, we really need for map updates and configuration updates to be atomic together in the same transaction. From a design standpoint, this probably means you'll need two different ways to update maps: the current method that updates in-memory with possibly a delayed or immediate sync, and a separate in-transaction update option that updates the configuration file and map files atomically and triggers a reload.

**Comment by amelhusic** [comment]
Hi,

With https://github.com/haproxytech/dataplaneapi/commit/e6a6f96bb73d22155810d0079fd98ba9eae1aaec it is possible to immediately sync map files. Hopefully this will solve your issue.
