### ISSUE TITLE
Posting the same backendswitchingrule returns 202 instead of 409

### ISSUE THREAD

**Issue by MartijnStraatman** [haproxytech/dataplaneapi#130]
Hi,

If I post the same backendswitchingrule (below) twice. I'd expect a http 409 but instead I receive a http 202.

```
{
  "cond": "if",
  "cond_test": "{ req_ssl_sni -i www.example.com }",
  "index": 8,
  "name": "backend-test"
}
```

Maybe I am missing something?

**Comment by oktalz** [comment]
hi @MartijnStraatman 
this is expected behavior, 
every resource that uses indexes behaves the same.

Otherwise, only way to insert data on certain index would meant that 
we need to delete all that are after it and then reinsert them again.
This is designed like that since order of, for example of backend switching rules (and other similar items in most cases) is 
extremely important in HAProxy 
(you can have different behavior if for example you mix allow and deny rules and then switch order of rules).

There is a bug in specification though, where 409 is mentioned as one possible response and it shouldn't be there, 
so that might give different clues. We will remove this from specification.

**Comment by MartijnStraatman** [comment]
Hi, 
Thanks for your reply. But I don't really understand it. How can I prevent the same backendswitching rule is added more than once?

**Comment by aiharos** [comment]
You could get the full list of rules and check if the rule you would like to add already exists at the right place. If not, take updating actions accordingly (removal, reordering, reinsertion), optionally in a transaction so that you can perform multiple changes at once.

Currently the dataplane does not inspect the contents of the rules during insertion, but we may consider improvements in this area in the future.
