### ISSUE TITLE
Using cookie with multiple space delimited params

### ISSUE THREAD

**Issue by mjuraga** [haproxytech/dataplaneapi#21]
it is not possible to use cookie with multiple space delimited params. Currently only cookie <name> is supported.

**Comment by mjuraga** [comment]
Fixed for now with https://github.com/haproxytech/dataplaneapi/commit/c0be0a2b94d3ff34c7dd861811ae57e1bed60daf

You can now enter multiple words to write all cookie parameters, this needs better definition in the spec and better validation.

**Comment by gitforbit** [comment]
Fixed with https://github.com/haproxytech/config-parser/pull/14/commits/9f415e124b5fc0c25f990540fabd4ccf985061ef

From now, only supported keywords are accepted as specified in documentation:
https://cbonte.github.io/haproxy-dconv/2.0/configuration.html#cookie%20(Alphabetically%20sorted%20keywords%20reference)
