### ISSUE TITLE
Consul discovery doesnt respect server_slots_base, server_slots_growth_increment parameters.

### ISSUE THREAD

**Issue by Efiartes** [haproxytech/dataplaneapi#265]
I add a consul server via dataplaneapi using the following curl request:
```
curl -u kr0m:PASSWORD \
       -H 'Content-Type: application/json' \
       -d '{
             "address": "192.168.69.50",
             "port": 8500,
             "enabled": true,
             "retry_timeout": 10,
             "server_slots_base": 1,
             "server_slots_growth_increment": 1,
             "server_slots_growth_type": "linear",
             "service_allowlist": ["web"]
           }' http://192.168.69.51:5555/v2/service_discovery/consul | jq
```

And i get:
```
{
  "address": "192.168.69.50",
  "enabled": true,
  "id": "43fb7b96-27a6-4f78-a29b-f5827d918b13",
  "port": 8500,
  "retry_timeout": 10,
  "server_slots_base": 10,
  "server_slots_growth_increment": 10,
  "server_slots_growth_type": "linear",
  "service-blacklist": null,
  "service-whitelist": null,
  "service_allowlist": [
    "web"
  ],
  "service_denylist": null
}
```

It ignored my server_slots_base and server_slots_growth_increment parameters.

By the way, i am using latest git cloned version of dataplaneapi compiled that way:
```
git clone https://github.com/haproxytech/dataplaneapi.git
cd dataplaneapi
make build
```

**Comment by prometherion** [comment]
Thanks for opening this issue @Efiartes.

The behaviour you're encountering seems counterintuitive but it has been done on purpose:

https://github.com/haproxytech/dataplaneapi/blob/2a955170d63abf15115c49d98e0422ce1d043187/discovery/utils.go#L56-L79

We deliberately decided to support a minimum of 10 server slots as the base since the Service Discovery automatically updates the list of available backends and minimises the HAProxy restart required when increasing the number of servers for a specific backend (please, correct me if I'm wrong @rmaticevic).

What we could improve from this is documenting that properly, any contribution is welcome, the file on which we could address it should be [this](https://github.com/haproxytech/dataplaneapi/blob/master/discovery/CONSUL.md) for Consul, although the same should be ported for AWS.

**Comment by Efiartes** [comment]
Thank you @prometherion for clarifiying my question, next time i will take a look at source code before answering or openning a issue.

Thanks for the time taken to answer.
