### ISSUE TITLE
Publish OpenAPI version of DP spec that aligns with DP master

### ISSUE THREAD

**Issue by akutz** [haproxytech/dataplaneapi#78]
Hi,

Related to #77 , can we please get the DP spec for OpenAPI that aligns with DP master? They could be published as assets in this repo. As it is, I have to manually modify things in the OpenAPI spec before generating client bindings, and that is an awful way to do things.

**Comment by akutz** [comment]
FYI, here are the steps I used to get the spec:

1. Build DP from `494f9b8` (`master` is broken)
2. Run DP
3. Run `curl http://DP_IP/v2/specification >dataplane-api-494f9b8.json`
4. Install a Swagger-to-OpenAPI conversion utility, ex. `npm install -g swagger2openapi`
5. Convert the spec `swagger2openapi dataplane-api-494f9b8.json >dataplane-api-494f9b8-openapi.json`
6. Run `make generate` from the Cluster API Provider for vSphere's [`Makefile`](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/master/contrib/haproxy/Makefile) since it removes errors in the DataPlane API spec that prevent it from being processed by the OpenAPI client generator.

**Comment by mjuraga** [comment]
Hi you can always find the latest spec here: https://github.com/haproxytech/dataplaneapi-specification/blob/master/build/haproxy_spec.yaml

If you want we can add openapi spec there too.

**Comment by akutz** [comment]
Hi @mjuraga ,

That would be *incredibly* helpful. I was literally just writing this:

```Makefile
## --------------------------------------
## Docker
## --------------------------------------
.PHONY: build-image
build-image: ## Builds the container image
	docker build -t haproxy .


## --------------------------------------
## DataPlane API OpenAPI spec
## --------------------------------------
.PHONY: build-spec
build-spec: build-image
build-spec: ## Builds the DataPlane API spec
	docker run -d --rm --name haproxy -p 5556:5556 haproxy
	curl \
	  --cacert example/ca.crt \
	  --cert example/client.crt --key example/client.key \
	  --user client:cert \
	  "https://localhost:5556/specification" >dataplane-api-swagger-$(DATAPLANEAPI_REF).json
	docker kill haproxy
	swagger2openapi "dataplane-api-$(DATAPLANEAPI_REF)-swagger.json" "dataplane-api-$(DATAPLANEAPI_REF)-openapi.json"	
```

**Comment by cjbrigato** [comment]
Hi,
I **second** this since I have to frequently generate go client bindings so converting first to a workable OpenAPI spec.

Just for the record, like @akutz I had to rework the spec to actually be usable after that, **but** in my book this step :
> Run make generate from the Cluster API Provider for vSphere's Makefile since it removes errors in the DataPlane API spec that prevent it from being processed by the OpenAPI client generator.

is a bit overkill. What I found sufficient to do was to convert to yaml, resolves internals and sanitize some escape failure : 

``` bash
curl -s -k -H "$AUTH_HEADER" https://XXXXXX/v2/specification > ${RECSPEC}
swagger2openapi -y --resolveInternal -f $RECSPEC > $OA3USPEC
cat $OA3USPEC | sed 's,\\s,\\\\s,g'| sed 's,\\d,\\\\d,g' > $DESTSPEC
```

**Comment by akutz** [comment]
Hi @cjbrigato,

> is a bit overkill

You say that...

> was to convert to yaml, resolves internals and sanitize some escape failure

But this is not obvious as a solution. I'm thrilled to learn of this, but calling the existing work-around overkill is a bit harsh IMO. I arrived at the current method by:

* Taking the published Open API spec
* Using Open API to generate client bindings
* Finding these bindings would not compile

I did not *start* from the Swagger spec since the published spec is already the Open API version. It seems you started from Swagger, went to Open API using a specific flag in the converter tool, underpants gnomes, and profit. As I said, I'm glad to know about this, but it starts from a much different place than where I started, so I'm not sure it's fair to compare the two.

**Comment by akutz** [comment]
Hi @cjbrigato,

Regardless of everything, I think what is absolutely clear is that HAProxy should use your `swagger2openapi` command line arguments and technique to generate their published Open API 3.0 spec to ensure it can be downloaded and compiled as-is.

**Comment by akutz** [comment]
Hi @cjbrigato,

So I just tried your method, and the resulting file still produces invalid Go code. Did you ever try generating Go code from the resulting spec? Because that is what my issue is. Please take a look at what the CAPV generation process has to do to convert the published spec into a valid Open API spec - https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/master/contrib/haproxy/Makefile.

Because without this post-processing, the published spec, whether used as-is or converted from Swagger, fails to compile in Go:

```shell
$ go build .
./api_backend_options.go:34:6: CreateAclOpts redeclared in this block
	previous declaration at ./api_acl.go:34:6
./api_backend_options.go:1516:6: DeleteAclOpts redeclared in this block
	previous declaration at ./api_acl.go:183:6
./api_backend_options.go:2588:6: GetAclOpts redeclared in this block
	previous declaration at ./api_acl.go:291:6
./api_backend_options.go:2707:6: GetAclsOpts redeclared in this block
	previous declaration at ./api_acl.go:410:6
./api_backend_options.go:5023:6: ReplaceAclOpts redeclared in this block
	previous declaration at ./api_acl.go:516:6
./api_filter.go:34:6: CreateFilterOpts redeclared in this block
	previous declaration at ./api_backend_options.go:183:6
./api_filter.go:183:6: DeleteFilterOpts redeclared in this block
	previous declaration at ./api_backend_options.go:1624:6
./api_filter.go:291:6: GetFilterOpts redeclared in this block
	previous declaration at ./api_backend_options.go:2813:6
./api_filter.go:410:6: GetFiltersOpts redeclared in this block
	previous declaration at ./api_backend_options.go:2932:6
./api_filter.go:516:6: ReplaceFilterOpts redeclared in this block
	previous declaration at ./api_backend_options.go:5175:6
./api_filter.go:516:6: too many errors
```

**Comment by cjbrigato** [comment]
Hi @akutz ,
Damn it's unbelivable how fast you answered my comment. Either you did a little fast or maybe it lies solely on my mediocre english (frenchy here you face ;)), but I'm more than sorry to see you received my comment has that "harsh", even to the point you felt you had to justify anything. It wasn't meant to be harsh. More than that it wasn't even made to be criticism of any sort, but to tell in case it would be of any help !

By the way I checked a little more and it seems that my method will NOT work, since I do not use the same generator, so I wasn't even aware of the bug you mention (for my own culture I read your issues on the generator github repo, very interesting), so the case is absolutely not comparable.
For the record, I use "https://github.com/danielgtaylor/openapi-cli-generator" which makes very simple, lightweight and unbelivably easy to customise go bindings. Other thing is it actually works despite duplication ;)

Hoping that you can read my comment a little better, because it is always sad to hurt anyhow by trying to help, so again, sorry for that.

Anyway on the primary subject, an embedded OpenAPI3 spec would be greatly appreciated, and would make some of us feeling better since the swagger spec is aging and all in all has quite a different paradigm that OpenApi3. OA3 can also evolve up to a point that such conversion will be either difficult or even not possible without hacking things in some way.
Is there any reason that could be disclosed to the profane on why HAproxy is keeping swagger instead of OA3 as it's specification of choice ? Would be more than interested in such knownledge.

thanx in advance !

**Comment by akutz** [comment]
Hi @cjbrigato,

> For the record, I use "https://github.com/danielgtaylor/openapi-cli-generator" which makes very simple, lightweight and unbelivably easy to customise go bindings. Other thing is it actually works despite duplication ;)

NICE! Yeah, I was using https://github.com/openapitools/openapi-generator-cli. I need to give your link a try and see if that does indeed solve this issue.

Regardless, I agree that HAProxy needs to decide the path forward with respect to the spec. I have a JIRA internally to convert to using the Swagger client bindings since I know HAProxy uses those internally. Even their existing models repo is based on the Swagger bindings - https://github.com/haproxytech/models. I only used Open API initially because of the published spec, but as we're close to having product based on all of this, I am concerned on relying on such a hack-y method to generate client bindings for Open API. Your link is a lifesaver!

**Comment by cjbrigato** [comment]
We got product based on the spec + the generator showed nearly since the beginning of the dataplane api, this seems stable enough for us, even we still tag the matter as non negligeable level of incertitude ;)

**Comment by mjuraga** [comment]
Hi @cjbrigato we are using Swagger 2.0 spec cause the https://github.com/go-swagger/go-swagger that we use for generating server-side code doesn't support OA3. That is the sole reason for that. If it's that big of a deal maybe we can work on having both of the specification embedded in the API.

**Comment by mjuraga** [comment]
@akutz this is still bugged: https://www.haproxy.com/documentation/dataplaneapi/latest/

We are working on fixing that.

**Comment by mjuraga** [comment]
Btw, now I figured out why you get OA3 spec on [docs](https://www.haproxy.com/documentation/dataplaneapi/latest/) it's what Redoc does, the HTML renderer for swagger docs, so that might cause confusion :)

**Comment by cjbrigato** [comment]
ha. @mjuraga that indeed make sense but the implication are quite definitive and may be a good occasion to hear from the team about their will on the matter : 
* indeed, go-swagger, from it's own name and how it is now clearly said by maintainers, doesn't and will never support OA3.
* That mean that if you want to migrate anyhow to OA3 and keep the generated server way, you'll have to migrate to a whole other generator, may it be *OpenAPITools/openapi-generator* or another contender
  * * and that mean that in such case you will not at all end with something comparable to the code go-swagger provided. 
  * * nearly all generators generated go code are comparable and interchangeable in principle, but this would still require a from scratch rework of whatever you overlayed the generated code with
  * * the other solution of providing yourself a "go-openapi3" of sort wich would produce same code from an OA3 spec is even more work, not reasonable for just keeping legacy behavior
This is, as said, because OA3 has strong paradigm differences than swagger, and so is way more complex.

Since swagger is more and more aging, this raise the concern for users like me (and like @akutz and much others I guess?) of maintainability and how much we can affort to ourself have some "debt" cause of the product we're building upon. That's why I would be *very* grateful to hear what are your (even if far concern) plan on this matter : keeping hard on go-swagger or organise some migration toward OA3 on the server side (and so you could now be dependant to OA3's will and ecosystem  waiting for the next thing you'll have to migrate for :p).
Maybe the concern was never raised and it's so far away that you don't even have plan or feeling that it needs to be addressed, that would be an answer too ^^'

So on my side it's not really a concern on the availability of the spec since you providing a converted spec or me converting your spec is even. It's more the feeling that the whole issue may soon be an ineluctable decision, maybe with breaking change or who knows, total turnover to some other way or technology.

I just hope that I'm not misunderstood and I'm not felt as intrusive hear. It's just that we rely _heavily_ on this whole and that If I can have insight on what will be breaking potentially in the next 9-36month, I'm allways feeling more geared toward future . Since we decided to tie ourself (with confidence) to HAproxy echosystem (and still I wasn't able to convince management to spend some more coin on enterprise-level part of the product so these whole concern would not have to be at all).

Thx in advance,;

**Comment by akutz** [comment]
What he said.

**Comment by akutz** [comment]
But in all seriousness, I completely agree with the above statement. I took a stab at switching to Go-Swagger client bindings, and as @cjbrigato said, it is technically possible, but the amount of work to switch is tremendous when there is heavy investment in OA3. And this is true for the other way as well.

The HAProxy documentation says in several places something like the following:

> the OpenAPI specification

It seems like the *intent* is to advertise an OA spec, even if that is not really the case.

Even if the HAProxy team wants to continue to use Go-Swagger internally for the server-side, it seems like a poor decision to rely on Swagger for client bindings

**Comment by mjuraga** [comment]
We've started development with OA3 in mind, but we found the OA3 tooling for server-side quite behind the OA2 tooling. 

We plan to convert to OA3 tooling for server-side when it matures enough. For now we plan to keep supporting both OA2 and OA3 specifications in parallel, by making sure to have any additions be able to be converted between them.

We will start including an OA3 version of the spec within the dataplane similar to how we serve the swagger spec now in one of the upcoming minor releases to save you guys the hassle of doing the conversion.

Also we will change our spec so it works with https://github.com/openapitools/openapi-generator-cli properly when generating the client bindings. This way the consumers should be able to use whatever tooling for the client-side regardless of what we four server-side code generation.

**Comment by cjbrigato** [comment]
> And that, kids, is a what we call an exact answer to precise concerns.
Thx and noted, I can now get back to life with more confidence and less insecurity feelings. 

(what I noted @akutz is that the OA3 tooling is not mature enough, which means that you'll have to make way much more PR against OA3 flaws to make it happen. :D )

**Comment by gitforbit** [comment]
Hi @akutz 

We added new endpoint `/specification_openapiv3` for converting spec from v2 to v3.
https://github.com/haproxytech/dataplaneapi-specification/commit/3e3de54e76b0c946d8f58120ba52027c4f51a1cf
https://github.com/haproxytech/dataplaneapi/commit/b1a296e3231877bcfe41d19b048a2e57d4acb4d2

**Comment by akutz** [comment]
![image](https://user-images.githubusercontent.com/101085/87697349-99860200-c757-11ea-96ce-b1930c707b94.png)

**Comment by akutz** [comment]
I am reopening this. The new URI works to pull the Open API schema, but the schema is still invalid :(

**Comment by amelhusic** [comment]
Hi @akutz 

With https://github.com/haproxytech/dataplaneapi/commit/1a392f5682290915665c356d323da031fd11b190 we removed multiple tags from spec, which caused openapi generator to generate duplicated structs.

I tested it with:
`openapi-generator generate -g go -i ~/Desktop/v3/v3-tags-ommited.json -o /tmp/go-bindings/ --package-name=dataplaneapi`
and it generates Go client without errors. I hope this will solve your issue.
